# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- id: release
  format: tar.gz
  # this name template makes the OS and Arch compatible with the results of `uname`.
  name_template: >-
    {{ .ProjectName }}_
    {{- title .Os }}_
    {{- if eq .Arch "amd64" }}x86_64
    {{- else if eq .Arch "386" }}i386
    {{- else }}{{ .Arch }}{{ end }}
    {{- if .Arm }}v{{ .Arm }}{{ end }}
  # use zip for windows archives
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
- name: go-archetype
  homepage: https://github.com/rantav/go-archetype
  description: "Dead simple project blueprints for the rest of us"
  license: "MIT"
  repository:
    owner: save-vi
    name: homebrew-tools
