name: Go
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and test
        run: make ci-test

      - name: Send code coverage report
        run: |
          bash <(curl -s https://codecov.io/bash)
          git checkout go.*
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      # TODO (@titusjaka): add .golangci.yml config and simplify this step
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.44.2
          args: >
            --fast 
            --enable-all 
            -D gochecknoglobals 
            -D gochecknoinits 
            -D prealloc 
            -D wsl
            -D forbidigo
            -D godot
            -D gofumpt
            -D gci
            -D ifshort
            -D nlreturn
            -D paralleltest
            -D tagliatelle
            -D testpackage