name: goreleaser

on:
  push:
    tags: "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

        - name: Set up Go 1.13
          uses: actions/setup-go@v1
          with:
            go-version: 1.13

        - name: Checkout
          uses: actions/checkout@master

        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@master
          with:
            version: v1
          env:
              GOPROXY: https://proxy.golang.org,direct
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
